insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('MY', 'Lesch, Kihn and Douglas', 629, 93, 'Natural Gas Distribution', '9252585');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('IT', 'Welch-Fay', 864, 56, 'Major Banks', '9151448');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Wisozk, Bins and Schneider', 839, 46, 'Medical/Dental Instruments', '0293898');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Breitenberg Inc', 39, 79, 'Computer Software: Prepackaged Software', '5375067');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('TW', 'Gusikowski, Reichel and Beahan', 147, 84, 'n/a', '3707554');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('NO', 'Smith Group', 51, 85, 'n/a', '4250866');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('PG', 'Bode, Greenholt and Morar', 523, 78, 'n/a', '0979157');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AZ', 'Lakin and Sons', 16, 58, 'n/a', '6615443');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('NP', 'Rice Inc', 649, 98, 'Real Estate Investment Trusts', '9903932');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('DE', 'Frami-Gleichner', 786, 65, 'Homebuilding', '9002829');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('TR', 'Hansen, Prohaska and D''Amore', 1000, 63, 'Electronic Components', '7102369');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Lesch, Luettgen and Bergnaum', 676, 23, 'Precious Metals', '1370422');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('RO', 'Shanahan-Skiles', 370, 65, 'Business Services', '3863403');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('BY', 'Koepp LLC', 834, 18, 'Real Estate Investment Trusts', '7708151');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('CA', 'Greenfelder-Ortiz', 849, 66, 'Real Estate Investment Trusts', '2956384');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AU', 'Schneider, Macejkovic and Botsford', 243, 87, 'n/a', '1352041');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('ID', 'Ullrich and Sons', 530, 68, 'Major Banks', '6765934');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('CA', 'Reichel-Dickens', 468, 32, 'n/a', '4349593');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Adams, Wilkinson and Bartoletti', 890, 10, 'Retail: Computer Software & Peripheral Equipment', '5233032');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('GT', 'Koepp Inc', 99, 96, 'Banks', '3694471');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AT', 'Connelly-Carroll', 811, 11, 'Business Services', '4776307');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Gislason Inc', 142, 30, 'n/a', '2312675');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AU', 'Hessel LLC', 805, 37, 'n/a', '7358670');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Harvey-Douglas', 717, 42, 'Finance: Consumer Services', '5575801');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('BR', 'Satterfield Group', 943, 23, 'Restaurants', '5543075');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('EC', 'Watsica LLC', 534, 18, 'Savings Institutions', '7448974');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Johnston-Runolfsson', 820, 70, 'Oilfield Services/Equipment', '6505538');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('BR', 'Yundt, Walter and Hermann', 970, 11, 'Biotechnology: In Vitro & In Vivo Diagnostic Substances', '0471997');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('BG', 'Lesch LLC', 402, 72, 'Homebuilding', '0237102');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('IN', 'Marks-Grant', 358, 99, 'Business Services', '0442485');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('GN', 'Thompson Group', 155, 70, 'Oil & Gas Production', '3505674');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Grant Group', 634, 79, 'Biotechnology: In Vitro & In Vivo Diagnostic Substances', '6198010');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('PG', 'Treutel Inc', 803, 85, 'Real Estate Investment Trusts', '3764416');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Kshlerin-Schaden', 314, 95, 'n/a', '7594434');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('PG', 'Crooks, Senger and Spencer', 564, 64, 'Trucking Freight/Courier Services', '6542348');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('IS', 'Padberg-Jacobson', 943, 96, 'Major Banks', '1359570');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('UZ', 'Leuschke Inc', 826, 79, 'Retail: Computer Software & Peripheral Equipment', '2465165');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('FJ', 'Huels Group', 659, 66, 'Savings Institutions', '4031729');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('ID', 'Green-Keebler', 72, 50, 'n/a', '3466400');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('FI', 'Powlowski-Goyette', 360, 48, 'n/a', '3539289');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('PK', 'Prohaska LLC', 629, 73, 'Computer Software: Prepackaged Software', '8308907');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('GA', 'Torp-White', 276, 62, 'Investment Bankers/Brokers/Service', '8061808');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('IT', 'Bauch, Zulauf and Stokes', 615, 21, 'Marine Transportation', '1701835');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('CO', 'Lemke-Frami', 675, 60, 'Marine Transportation', '2754059');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('CN', 'Reinger-Price', 108, 35, 'Major Banks', '5239011');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('RU', 'Reichert-Vandervort', 264, 31, 'Advertising', '2204962');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('RO', 'Larson, Waelchi and Rice', 486, 99, 'Oil & Gas Production', '2160853');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AR', 'Keeling, Yost and Goldner', 959, 81, 'Property-Casualty Insurers', '2567168');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('GA', 'Altenwerth-Bins', 605, 57, 'Property-Casualty Insurers', '5746662');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('CR', 'Schmidt, Oberbrunner and D''Amore', 790, 3, 'Automotive Aftermarket', '5590831');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('ZA', 'Swaniawski, Legros and Ryan', 251, 69, 'Precious Metals', '5020683');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AU', 'White and Sons', 727, 65, 'Professional Services', '1439554');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Reilly and Sons', 61, 74, 'Meat/Poultry/Fish', '6452837');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('NP', 'Mosciski-Rolfson', 421, 34, 'n/a', '8383245');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('UA', 'Baumbach and Sons', 436, 91, 'Electrical Products', '7267893');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('IT', 'Rutherford-VonRueden', 320, 99, 'Computer Software: Prepackaged Software', '9292735');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('NO', 'Runolfsson, Cronin and Hermiston', 843, 56, 'Medical Specialities', '6881565');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('LK', 'Purdy-Shields', 138, 40, 'Transportation Services', '7362567');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Fisher and Sons', 678, 32, 'Real Estate Investment Trusts', '3880592');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('DO', 'Mann, Gusikowski and Abernathy', 485, 18, 'n/a', '0071284');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('PG', 'Abshire, Green and Tromp', 719, 57, 'n/a', '2127810');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Beahan-Herman', 989, 59, 'n/a', '7333748');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Windler, Botsford and Auer', 469, 53, 'n/a', '3730516');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('NA', 'Pacocha, Nicolas and Hills', 86, 4, 'Mining & Quarrying of Nonmetallic Minerals (No Fuels)', '7745275');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('PK', 'Will-Dietrich', 701, 31, 'Computer Software: Prepackaged Software', '2006445');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('CD', 'Jones, Parisian and McGlynn', 157, 17, 'Construction/Ag Equipment/Trucks', '3891860');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('ZA', 'Hills Inc', 369, 83, 'Real Estate Investment Trusts', '1483996');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('BD', 'Heaney-Denesik', 493, 91, 'Recreational Products/Toys', '7430978');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Bailey, Witting and Schulist', 434, 69, 'Investment Managers', '6096444');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AR', 'Effertz-Gerhold', 654, 58, 'Biotechnology: Commercial Physical & Biological Resarch', '3380304');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('GA', 'Towne LLC', 768, 95, 'Auto Manufacturing', '6941752');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('BZ', 'Klocko-Hayes', 677, 80, 'n/a', '5062058');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AU', 'Rodriguez-Corkery', 107, 5, 'Telecommunications Equipment', '7840981');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AU', 'Howe LLC', 215, 21, 'n/a', '3391264');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('BR', 'Satterfield-Nikolaus', 869, 14, 'Property-Casualty Insurers', '2210060');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('PG', 'Haag LLC', 199, 48, 'n/a', '4907691');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AU', 'Turcotte and Sons', 17, 68, 'Precious Metals', '0823154');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Ritchie and Sons', 170, 83, 'Books', '1007135');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('MM', 'Lynch Group', 623, 89, 'Construction/Ag Equipment/Trucks', '8407352');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('BR', 'Schowalter-Corkery', 989, 3, 'Real Estate Investment Trusts', '1077088');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('AU', 'Schulist-Willms', 547, 24, 'Diversified Commercial Services', '8638321');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('GT', 'Kilback, Mitchell and Mayer', 573, 74, 'Other Consumer Services', '0750978');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('FR', 'Little, Parisian and Borer', 335, 22, 'Newspapers/Magazines', '4383684');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('CA', 'Kemmer-Huel', 207, 67, 'n/a', '2635122');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('RU', 'Beahan, Lindgren and Sipes', 133, 13, 'Computer Software: Prepackaged Software', '3398165');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('DE', 'Cummings-Christiansen', 110, 88, 'Electric Utilities: Central', '9962064');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Funk LLC', 51, 67, 'n/a', '0689610');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('SS', 'Farrell-Breitenberg', 146, 46, 'Real Estate Investment Trusts', '8410855');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Schmeler, Beahan and Thompson', 265, 40, 'Investment Bankers/Brokers/Service', '3912908');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Bartell Group', 806, 76, 'n/a', '6858067');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('GB', 'Wilkinson Group', 881, 59, 'n/a', '9415132');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('PH', 'Cronin-White', 161, 54, 'Finance: Consumer Services', '8499943');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('TC', 'Reilly, Tromp and Hegmann', 892, 40, 'Steel/Iron Ore', '5195489');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('CF', 'Kautzer, Gerhold and Kshlerin', 151, 72, 'n/a', '7730834');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Bergstrom, Fadel and Kihn', 708, 72, 'Semiconductors', '7748302');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('RU', 'Goodwin Inc', 138, 98, 'Medical/Dental Instruments', '4361407');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('IN', 'Okuneva, Stoltenberg and Gottlieb', 253, 68, 'n/a', '4720343');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('CO', 'Nolan-Von', 487, 99, 'n/a', '8862835');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('US', 'Beahan-Stroman', 989, 42, 'n/a', '3782154');
insert into Stocks (Symbol, CompanyName, Purchase, LastDiv, Industry, MarketCap) values ('MH', 'Moen Inc', 742, 77, 'Other Specialty Stores', '5721503');
